core/urls.py
from django.contrib import admin
from django.urls import include, path
import reclamacoes
import usuarios
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('reclamacoes.urls')),
    path('usuarios/',include('usuarios.urls'))
]

reclamacoes/urls.py
from django.urls import path
from . import views
app_name = 'reclamacoes'

urlpatterns = [
    path('', views.home, name='home'),
    path('cadastrarempresa/',views.cadastrar_empresa,name='cadastrar_empresa'),
    path('reclame/<int:empresa_id>/', views.criar_reclamacao, name='criar_reclamacao'),
    path('vermais/<int:empresa_id>/', views.ver_mais_empresa, name='ver_mais_empresa'),
    path('vermais/reclamacao/<int:reclamacao_id>/',views.ver_mais_reclamacao,name='ver_mais_reclamacao'),
    path('area_admin/',views.area_admin,name='area_admin'),
    path('denunciar/<int:reclamacao_id>/',views.denunciar,name="denunciar"),
    path('bloquear/<int:reclamacao_id>/',views.bloquear,name='bloquear'),
    path('desbloquear/<int:reclamacao_id>/',views.desbloquear,name='desbloquear'),
    path('aprovar/<int:empresa_id>/', views.aprovar, name='aprovar'),
    path('rejeitar/<int:empresa_id>/', views.rejeitar, name='rejeitar'),
    path('ler_denuncias/<int:reclamacao_id>/', views.ler_denuncias, name='ler_denuncias'),
    path('delete_denuncia/<int:denuncia_id>/', views.deletar_denuncia, name='delete_denuncia'),

]

usuarios/urls.py
from django.urls import path
from . import views
app_name = 'usuarios'  

urlpatterns = [
    path('registro/', views.cadastro_view, name='registro'),
    path('login/', views.login_usuario, name='login'),
    path('logout/', views.logout, name='logout'),
]

reclamacoes/models.py
from django.db import models
from django.contrib.auth.models import User

class Empresa(models.Model):
    nome = models.CharField(max_length=50)
    cnpj = models.CharField(max_length=14, unique=True)
    aprovar = models.BooleanField(default=False,blank=True, null= True)
    rejeitar = models.BooleanField(blank=True, null= True)
    def __str__(self):
        return self.nome


class Reclamacao(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100) 
    descricao = models.TextField()            
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)
    denuncias_count = models.PositiveIntegerField(default=0)
    bloquear = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.titulo} - {self.empresa.nome}"

class Denuncia(models.Model):
    MOTIVOS = [
        ('SPAM', 'Conteúdo inadequado'),
        ('OFENSIVO', 'Linguagem ofensiva'),
        ('FALSO', 'Informação falsa'),
        ('OUTRO', 'Outro motivo'),
    ]

    reclamacao = models.ForeignKey(Reclamacao, on_delete=models.CASCADE, related_name='denuncias')
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL,null= True) 
    motivo = models.CharField(max_length=20, choices=MOTIVOS)
    comentario = models.TextField(blank=True, null=True)
    criado_em = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Denúncia por {self.usuario} em {self.reclamacao.titulo}"

reclamacoes/forms.py
from django import forms
from .models import Empresa, Reclamacao, Denuncia

class EmpresaForm(forms.ModelForm):
    class Meta():
        model = Empresa
        fields = ['nome', 'cnpj']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-input'}),
            'cnpj': forms.TextInput(attrs={'class': 'form-input', 'inputmode': 'numeric','maxlength': '14','placeholder': 'Digite apenas números'}),
        }

    def clean_cnpj(self):
        cnpj = self.cleaned_data.get('cnpj')
        if not cnpj.isdigit():
            raise forms.ValidationError("O CNPJ deve conter apenas números.")
        if len(cnpj) != 14:
            raise forms.ValidationError("O CNPJ deve conter exatamente 14 números.")
        return cnpj
    
class ReclamacaoForm(forms.ModelForm):
    class Meta():
        model = Reclamacao
        fields = ['titulo','descricao',]
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-input'}),
            'descricao': forms.Textarea(attrs={'class': 'form-input'}),
        }

class DenunciaForm(forms.ModelForm):
    class Meta():
        model = Denuncia
        fields = ['motivo', 'comentario']
        widgets = {
            'motivo': forms.Select(attrs={'class': 'form-input'}),
            'comentario': forms.Textarea(attrs={'class': 'form-input'}),
        }

reclamacoes/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import Empresa,Reclamacao,Denuncia
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required,user_passes_test
from .forms import EmpresaForm, ReclamacaoForm,DenunciaForm
from django.contrib import messages

def home(request):
    empresa = Empresa.objects.all().filter(aprovar=True,rejeitar = False)
    return render(request,'pages/home.html',{'empresa':empresa})


def ver_mais_empresa(request,empresa_id):
    empresa = get_object_or_404(Empresa,pk=empresa_id)
    reclamacoes = Reclamacao.objects.filter(empresa=empresa).order_by('-criado_em').filter(bloquear=False)
    return render(request, 'pages/ver_mais_empresa.html', {'empresa': empresa,'reclamacoes': reclamacoes})


@login_required(login_url='/login/')
def cadastrar_empresa(request):
    if request.method == 'POST':
        form = EmpresaForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Empresa cadastrada com sucesso! Aguarde a aprovação.')
            return redirect('reclamacoes:home')
        else:
            messages.error(request, 'Por favor, corrija os erros abaixo.')
            return render(request,'pages/cadastro_empresa.html',{'form':form})
    else:
        form = EmpresaForm()
    return render(request,'pages/cadastro_empresa.html',{'form':form})


def ver_mais_reclamacao(request,reclamacao_id):
    reclamacao = get_object_or_404(Reclamacao,pk=reclamacao_id)
    return render(request,'pages/ver_mais_reclamacao.html',{'reclamacao':reclamacao})

@login_required(login_url='/login/')
def criar_reclamacao(request, empresa_id):
    empresa = get_object_or_404(Empresa, pk=empresa_id)
    if request.method == 'POST':
        form = ReclamacaoForm(request.POST)
        if form.is_valid():
            reclamacao = form.save(commit=False)
            reclamacao.empresa = empresa
            reclamacao.usuario = request.user
            reclamacao.save()
            messages.success(request,'Reclamação realizada com sucesso!')
        else:
            messages.error(request,'Por favor, corrija os erros abaixo.')
            return render(request, 'pages/criar_reclamacao.html', {'form': form, 'empresa':empresa})
    else:
        form =ReclamacaoForm()

    return render(request, 'pages/criar_reclamacao.html', {'form': form, 'empresa':empresa})

@user_passes_test(lambda u: u.is_staff, login_url='/login/')
def area_admin(request):
    reclamacoes_denuncias = Reclamacao.objects.filter(bloquear=False).order_by('-denuncias_count')
    reclamacoes = Reclamacao.objects.filter(bloquear=True).order_by('-denuncias_count')
    empresas = Empresa.objects.filter(aprovar=False)
    empresas_aprovadas = Empresa.objects.filter(aprovar=True, rejeitar=False)
    empresas_rejeitadas = Empresa.objects.filter(rejeitar=True)

    return render(request,'pages/adminpage.html',{'reclamacoes_denuncias': reclamacoes_denuncias,'reclamacoes': reclamacoes,'empresas': empresas,'empresas_aprovadas': empresas_aprovadas,'empresas_rejeitadas': empresas_rejeitadas})


def denunciar(request,reclamacao_id):
    reclamacao = get_object_or_404(Reclamacao,pk=reclamacao_id)
    if request.method == "POST":
        form = DenunciaForm(request.POST)
        if form.is_valid():
            denuncia = form.save(commit=False)
            denuncia.usuario = request.user
            denuncia.reclamacao = reclamacao
            denuncia.save()

            reclamacao.denuncias_count += 1
            reclamacao.save()
            return redirect('reclamacoes:home')
    else:
        form = DenunciaForm()

    return render(request,'pages/denunciar.html',{'form':form,'reclamacao':reclamacao})


def bloquear(request,reclamacao_id):
    reclamacao = get_object_or_404(Reclamacao,pk=reclamacao_id)

    if request.method=='POST':
        reclamacao.bloquear = True
        reclamacao.save()

    return redirect('reclamacoes:area_admin')



def desbloquear(request,reclamacao_id):
    reclamacao = get_object_or_404(Reclamacao,pk=reclamacao_id)

    if request.method=='POST':
        reclamacao.bloquear = False
        reclamacao.save()

    return redirect('reclamacoes:area_admin')


def aprovar(request,empresa_id):
    empresa = get_object_or_404(Empresa,pk=empresa_id)

    if request.method=='POST':
        empresa.aprovar = True
        empresa.rejeitar = False
        empresa.save()

    return redirect('reclamacoes:area_admin')


def rejeitar(request,empresa_id):
    empresa = get_object_or_404(Empresa,pk=empresa_id)

    if request.method=='POST':
        empresa.aprovar = None
        empresa.rejeitar = True
        empresa.save()

    return redirect('reclamacoes:area_admin')

def ler_denuncias(request, reclamacao_id):
    denuncias = Denuncia.objects.all().order_by('-criado_em')
    reclamacao = get_object_or_404(Reclamacao,pk=reclamacao_id)
    empresa = get_object_or_404(Empresa,pk=reclamacao.empresa.id)
    return render(request,'pages/ler_denuncias.html',{'denuncias':denuncias,'reclamacao':reclamacao,'empresa':empresa})

def deletar_denuncia(request, denuncia_id):
    denuncia = get_object_or_404(Denuncia,pk=denuncia_id)
    reclamacao = get_object_or_404(Reclamacao,pk=denuncia.reclamacao.id)

    if request.method=='POST':
        reclamacao.denuncias_count -= 1
        reclamacao.save()
        denuncia.delete()

    return redirect('reclamacoes:ler_denuncias', reclamacao.id)

reclamacoes/templates/partials/auth-actions.html
{% if user.is_authenticated %}
    {% if user.is_staff or user.is_superuser %}
        {% if request.path != '/area_admin/' %}
            <a href="{% url 'reclamacoes:area_admin' %}" class="btn btn-login">
                <span class="auth-text">Painel Admin</span>
            </a>
        {% endif %}
    {% endif %}

<a href="{% url 'reclamacoes:cadastrar_empresa' %}" class="btn btn-login">
    <span class="auth-text">Cadastrar Empresa</span>
</a>
{% else %}
    <a href="{% url 'usuarios:login' %}" class="btn btn-login">
        <span class="auth-text">Acessar</span>
    </a>
    <a href="{% url 'usuarios:registro' %}" class="btn btn-signup">
        <span class="auth-text">Criar Conta</span>
    </a>

{% endif %}
    <a href="{% url 'usuarios:logout' %}" class="btn btn-logout">
        <span class="auth-text">Sair</span>
    </a>

reclamacoes/templates/partials/empresa.html
<article class="item-card square-card">
    <div class="item-content">
        <h2 class="item-title">{{ empresa.nome|truncatechars:30 }}</h2>
        <div class="item-actions">
            <a href="{% url "reclamacoes:ver_mais_empresa" empresa.id %}" class="btn btn-primary">
                Ver Mais
            </a>                            
            <a href="{% url "reclamacoes:criar_reclamacao" empresa.id %}" class="btn btn-primary">
                Reclamar
            </a>
        </div>
    </div>
</article>

reclamacoes/templates/partials/footer.html
<footer class="main-footer wrapper">
    <div class="container footer-content">
        <div class="developer">
        <a href="https://github.com/KauanMonteiro" target="_blank" rel="noreferrer noopener">By Kauãn Monteiro</a>
        </div>
    
        <div class="powered">
        <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
        </div>
    </div>
  </footer>

reclamacoes/templates/partials/head.html
{% load static %}
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
        integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">


    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Reclame</title>
</head>

reclamacoes/templates/partials/header.html
{% include "partials/head.html" %}
<header class="main-header">
    <div class="container main-header-container">
        <a href="/" class="main-logo">
            Reclamações
        </a>
        
        <form class="search-form">
            <input type="search" class="search-input" placeholder="Pesquisar...">
            <button type="submit" class="search-button">🔍</button>
        </form>
        {% include "partials/auth-actions.html" %}

    </div>
</header>

reclamacoes/templates/partials/message.html
{% if messages %}
<div class="main-content center container messages-container">    
    {% for message in messages %}
        <div class="message {{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
</div>
{% endif %}

reclamacoes/templates/partials/reclamacao.html
<div class="reclamacao-card">
    <div class="cabecalho-reclamacao">
        <h3 class="titulo-reclamacao">{{ reclamacao.titulo|truncatechars:25}}</h3>
        <div class="meta-info">
            <span class="usuario">
                <i class="fas fa-user"></i>
                {{ reclamacao.usuario.username }}
            </span>
            <span class="data">
                <i class="fas fa-calendar-alt"></i>
                {{ reclamacao.criado_em|date:"d/m/Y H:i" }}
            </span>
        </div>
    </div>
    
    <div class="preview-descricao">
        {{ reclamacao.descricao|truncatechars:25 }}
    </div>
    
    <div class="rodape-reclamacao">
        <a href="{% url "reclamacoes:ver_mais_reclamacao" reclamacao.id %}" class="btn btn-primary">
            Ver Completo
        </a>
    </div>
</div>